import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div className="flex flex-col flex-1  items-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" w-full">Test</div>
      <Link href="/profile">
        <a className="text-4xl  ">Here</a>
      </Link>
      <div className="h-5 w-full "></div>
    </div>
  );
}
